name       : stunnel
version    : 5.44
release    : 1
source     :
    - https://www.stunnel.org/downloads/stunnel-5.44.tar.gz : 990a325dbb47d77d88772dd02fbbd27d91b1fea3ece76c9ff4461eca93f12299
license    : GPL-2.0
component  : network.util
summary    : TLS offloading and load-balancing proxy
description: |
    The stunnel program is designed to work as TLS encryption wrapper between remote clients and local (inetd-startable) or remote servers. The concept is that having non-TLS aware daemons running on your system you can easily set them up to communicate with clients over secure TLS channels.
    
    stunnel can be used to add TLS functionality to commonly used Inetd daemons like POP-2, POP-3, and IMAP servers, to standalone daemons like NNTP, SMTP and HTTP, and in tunneling PPP over network sockets without changes to the source code.
setup      : |
    %patch -p1 < $pkgfiles/stunnel-systemd-service.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 $installdir/usr/share/doc/stunnel/examples/stunnel.service -t $installdir/%libdir%/systemd/system

    rm $installdir/usr/share/doc/stunnel/INSTALL.{W32,WCE}
    rm $installdir/usr/share/doc/stunnel/examples/stunnel.{rh.init,spec}
