name       : stunnel
version    : '5.53'
release    : 7
source     :
    - https://www.stunnel.org/downloads/archive/5.x/stunnel-5.53.tar.gz : 80439896ee14269eb70bc8bc669433c7d619018a62c9f9c5c760a24515302585
license    : GPL-2.0-or-later
component  : network.util
summary    : TLS offloading and load-balancing proxy
description: |
    The stunnel program is designed to work as TLS encryption wrapper between remote clients and local (inetd-startable) or remote servers. The concept is that having non-TLS aware daemons running on your system you can easily set them up to communicate with clients over secure TLS channels.

    stunnel can be used to add TLS functionality to commonly used Inetd daemons like POP-2, POP-3, and IMAP servers, to standalone daemons like NNTP, SMTP and HTTP, and in tunneling PPP over network sockets without changes to the source code.
builddeps  :
    - nmap     # check
setup      : |
    %patch -p1 < $pkgfiles/0001-stunnel-service-privatetmp.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 $installdir/usr/share/doc/stunnel/examples/stunnel.service -t $installdir/%libdir%/systemd/system

    rm $installdir/usr/share/doc/stunnel/INSTALL*
    rm $installdir/usr/share/doc/stunnel/examples/stunnel.{rh.init,spec}
check      : |
    %make check
